{% set name = "workflows" %}
{% set version = "1.7.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21ed4c39a495c34fd055c52a67dbe3d88e417a09b289bdf1aaa3d3db9568d146
build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - enum34  # [py2k]
    - python
    - setuptools
    - six
    - stomp.py <5.0

test:
  imports:
    - workflows
    - workflows.contrib
    - workflows.frontend
    - workflows.logging
    - workflows.recipe
    - workflows.services
    - workflows.transport
    - workflows.util

about:
  home: https://github.com/DiamondLightSource/python-workflows
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Data processing in distributed environments
  doc_url: https://github.com/DiamondLightSource/python-workflows
  dev_url: https://github.com/DiamondLightSource/python-workflows

extra:
  recipe-maintainers:
    - anthchirp
