{% set name = "workflows" %}
{% set version = "2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 923c7aea841ab3cff95710d6d72e0c1a472bec0e94fc9c524a19f9e2303787ab
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - setuptools
    - stomp.py

test:
  imports:
    - workflows
    - workflows.contrib
    - workflows.frontend
    - workflows.logging
    - workflows.recipe
    - workflows.services
    - workflows.transport
    - workflows.util

about:
  home: https://github.com/DiamondLightSource/python-workflows
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Data processing in distributed environments
  doc_url: https://github.com/DiamondLightSource/python-workflows
  dev_url: https://github.com/DiamondLightSource/python-workflows

extra:
  recipe-maintainers:
    - anthchirp
