{% set name = "workflows" %}
{% set version = "2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e3cb4af6a29201fea15aa77ba535c56935e4ca93ad16f2f1a80caa0c5f4950cd
build:
  noarch: python
  number: 0
  entry_points:
    - workflows.validate_recipe = workflows.recipe.validate:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pika
    - python >=3.6
    - setuptools
    - stomp.py <6.1.1

test:
  imports:
    - workflows
    - workflows.contrib
    - workflows.frontend
    - workflows.logging
    - workflows.recipe
    - workflows.services
    - workflows.transport
    - workflows.util
  commands:
    - pip check
    - workflows.validate_recipe --help
  requires:
    - pip

about:
  home: https://pypi.python.org/pypi/workflows
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Data processing in distributed environments
  doc_url: https://github.com/DiamondLightSource/python-workflows
  dev_url: https://github.com/DiamondLightSource/python-workflows

extra:
  recipe-maintainers:
    - anthchirp
