{% set name = "workflows" %}
{% set version = "1.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0101d1c8796de232699bbfb3451fa7a43c645cd58fd8aa1f5102ea7262666eca
build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - enum34  # [py2k]
    - python
    - setuptools
    - six
    - stomp.py

test:
  imports:
    - workflows
    - workflows.contrib
    - workflows.frontend
    - workflows.logging
    - workflows.recipe
    - workflows.services
    - workflows.transport
    - workflows.util

about:
  home: https://github.com/DiamondLightSource/python-workflows
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Data processing in distributed environments
  doc_url: https://github.com/DiamondLightSource/python-workflows
  dev_url: https://github.com/DiamondLightSource/python-workflows

extra:
  recipe-maintainers:
    - anthchirp
