travis:
  secure:
    BINSTAR_TOKEN: geFzJLbRNNDEZDxkfS7nK+BjhuIu1+Ca/3OrHLmWZnb/YKAWsRI9nj9eOmkT7aiLwjVlAh9i827G/V0FyAkOScnoJDIMAhqAJ35h/CVAGeI1TCRk6A7bDrJ4BrRoaGDrcHxCqq3gCDRlfPGWPSLI52fYc8ED0P5MOef5DSAOZVOyOTORfMmdB7YgNbpyPg2lqyltKxYbbun4HgTl2/LzU+kMwwlHd0OAMAHSZ3kZt1r+4uJaoKsgLCzPKZewoKCuYeSNxc1jMbUk7iKPgH1tEZ3H+ZVAZo4tjoZpa4eTnP48XvClO+hYfquojkUu96RVuYwuHDFF1DKoAWklyXyy5ZI8xUxw3Kda9qLU2de8qCoo+XB31DWi9ssSmzsM0ElxZQafDnA4IuTOqsJpQ9xzIvhripAFJvZWCtp4s78okDzdtQ15sjW0hLrbjB2PshvLyN0swWwEqOnPrn7TFdbYNEKCplo96PvS04IIf2Wy/8+4A7oLE1r5siWj7eTL50yRXkFatMdwlfAl4YaGYblS5MkidATmkmcer/wFKZJ+jRPQNmeWYXtF2YtmjIskXCMOacImhecW0zlupsoE20P6QWCGrE8A7J0cif+U6IPl10RSRtu+Tt3cHjFzN/3TsqxaXk4aHxbyYDV0mmvv7+ac8M+Hla2SXYmITymYBMP92Y8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
